#!/bin/bash

while [[ True ]]; do
    mosquitto_pub -h mqtt.eclipseprojects.io -t econam01 -m "{\"variable\":\"vazao\", \"value\":$(($RANDOM%151)),\"unit\":\"L/Min\"}"
    mosquitto_pub -h mqtt.eclipseprojects.io -t econam01 -m "{\"variable\":\"totalizador_de_vazao\", \"value\":$(($RANDOM%151)),\"unit\":\"L/Min\"}"
    mosquitto_pub -h mqtt.eclipseprojects.io -t econam01 -m "{\"variable\":\"corrente\", \"value\":$(($RANDOM%151)),\"unit\":\"A\"}"
    mosquitto_pub -h mqtt.eclipseprojects.io -t econam01 -m "{\"variable\":\"setpoint\", \"value\":$(($RANDOM%151)),\"unit\":\"A\"}"
    mosquitto_pub -h mqtt.eclipseprojects.io -t econam01 -m "{\"variable\":\"bolsa_de_lodo\", \"value\":$(($RANDOM%151)),\"unit\":\"%\"}"
    mosquitto_pub -h mqtt.eclipseprojects.io -t econam01 -m "{\"variable\":\"tipo_de_energia\", \"value\":$(($RANDOM%2)),\"unit\":\"boolean\"}"
    mosquitto_pub -h mqtt.eclipseprojects.io -t econam01 -m "{\"variable\":\"caixa_agua\", \"value\":$(($RANDOM%151)),\"unit\":\"%\"}"
    mosquitto_pub -h mqtt.eclipseprojects.io -t econam01 -m "{\"variable\":\"inicializar\", \"value\":$(($RANDOM%2)),\"unit\":\"boolean\"}"
    mosquitto_pub -h mqtt.eclipseprojects.io -t econam01 -m "{\"variable\":\"tipo_de_rede\", \"value\":$(($RANDOM%2)),\"unit\":\"boolean\"}"
    mosquitto_pub -h mqtt.eclipseprojects.io -t econam01 -m "{\"variable\":\"modo_de_operação\", \"value\":$(($RANDOM%2)),\"unit\":\"\"}"
    mosquitto_pub -h mqtt.eclipseprojects.io -t econam01 -m "{\"variable\":\"vazao_agua_potavel\", \"value\":$(($RANDOM%151)),\"unit\":\"L/Min\"}"
    mosquitto_pub -h mqtt.eclipseprojects.io -t econam01 -m "{\"variable\":\"vazao_esgoto_tratado\", \"value\":$(($RANDOM%151)),\"unit\":\"L/Min\"}"
    mosquitto_pub -h mqtt.eclipseprojects.io -t econam01 -m "{\"variable\":\"consumo_de_energia\", \"value\":$(($RANDOM%151)),\"unit\":\"KWh\"}"
    mosquitto_pub -h mqtt.eclipseprojects.io -t econam01 -m "{\"variable\":\"nivel_por_batelada\", \"value\":$(($RANDOM%151)),\"unit\":\"cm\"}"
    mosquitto_pub -h mqtt.eclipseprojects.io -t econam01 -m "{\"variable\":\"volume_de_gases\", \"value\":$(($RANDOM%151)),\"unit\":\"M3\"}"
    mosquitto_pub -h mqtt.eclipseprojects.io -t econam01 -m "{\"variable\":\"tempo_de_uso\", \"value\":$(($RANDOM%151)),\"unit\":\"H\"}"
    mosquitto_pub -h mqtt.eclipseprojects.io -t econam01 -m "{\"variable\":\"ph\", \"value\":$(($RANDOM%151)),\"unit\":\"\"}"
    mosquitto_pub -h mqtt.eclipseprojects.io -t econam01 -m "{\"variable\":\"turbidez\", \"value\":$(($RANDOM%151)),\"unit\":\"UNT\"}"
    mosquitto_pub -h mqtt.eclipseprojects.io -t econam01 -m "{\"variable\":\"dqo\", \"value\":$(($RANDOM%151)),\"unit\":\"mgO2/L\"}"
    sleep 30s
done
