#!/bin/bash

while [[ True ]]; do
    mosquitto_pub -h mqtt.eclipseprojects.io -t econam01 -m "{\"variable\":\"lat\", \"value\":$(($RANDOM%151)),\"unit\":\"\"}"
    mosquitto_pub -h mqtt.eclipseprojects.io -t econam01 -m "{\"variable\":\"long\", \"value\":$(($RANDOM%151)),\"unit\":\"\"}"
    mosquitto_pub -h mqtt.eclipseprojects.io -t econam02 -m "{\"variable\":\"lat\", \"value\":$(($RANDOM%151)),\"unit\":\"\"}"
    mosquitto_pub -h mqtt.eclipseprojects.io -t econam02 -m "{\"variable\":\"long\", \"value\":$(($RANDOM%151)),\"unit\":\"\"}"
    sleep 30s
done
