version: "3.8"
services:
  postgres:
    image: "postgres"
    container_name: postgres
    hostname: localhost
    restart: on-failure
    volumes:
      - "./volumes/postgres/_data:/var/lib/postgresql/data"
    ports:
      - ${DBPORT}:${DBPORT}
    environment:
      POSTGRES_PASSWORD: ${DBPASS}
      POSTGRES_DB: ${DB}
      POSTGRES_USER: ${DBUSER}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  influx:
    image: "influxdb"
    container_name: "influxdb"
    ports:
      - 8086:8086
    volumes:
      - "./volumes/influx/influxdb/:/var/lib/influxdb"
      - "./volumes/influx/influxdb2/:/var/lib/influxdb2"
  grafana:
    image: "grafana/grafana"
    container_name: grafana
    ports:
      - 3001:3000
    volumes:
      - "./volumes/grafana/dashboards:/var/lib/grafana/dashboards"
      - "./volumes/grafana/datasources:/etc/grafana/datasources"
      - "./volumes/grafana/plugins:/var/lib/grafana/plugins"
      - "./volumes/grafana/grafana_data:/var/lib/grafana"
  mosquitto:
    image: eclipse-mosquitto:1.6.14
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "./volumes/mosquitto/mosquitto.conf:/var/lib/mosquitto/config/mosquitto.conf"