version: "3.8"
services:
  postgres:
    image: "postgres"
    shm_size: 1g
    container_name: "postgres"
    hostname: "localhost"
    restart: on-failure
    volumes:
      - "/opt/databases/volume-econam/_data:/var/lib/postgresql/data"
    ports:
      - ${DBPORT}:${DBPORT}
    environment:
      POSTGRES_PASSWORD: ${DBPASS}
      POSTGRES_DB: ${DB}
      POSTGRES_USER: ${DBUSER}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  grafana:
    image: "grafana/grafana"
    shm_size: 1g
    ports:
      - 3001:3000
    volumes:
      - "./config/dashboards:/var/lib/grafana/dashboards"
      - "./config/datasources:/etc/grafana/datasources"
      - "./config/plugins:/var/lib/grafana/plugins"
      - "./grafana_data:/var/lib/grafana"
  mosquitto:
    image: eclipse-mosquitto:1.6.14
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "./mosquitto/mosquitto.conf:/var/lib/mosquitto/config/mosquitto.conf"
  machbase:
    image: "machbase/machbase"
    hostname: machbase
    container_name: machbase
    expose:
      - "5001"
      - "5656"
    ports:
      - "5001:5001"
      - "5656:5656"